
CREATE TABLE cbc (
    id int(10) unsigned NULL,
    fullname varchar(255) NULL,
    date_of_birth date NULL,
    gender varchar(255) NULL,
    pb_district varchar(255) NULL,
    pb_country varchar(255) NULL,
    pb_subcounty varchar(255) NULL,
    pb_parish varchar(255) NULL,
    pb_village varchar(255),
    cr_district varchar(255) NULL,
    cr_country varchar(255) NULL,
    cr_subcounty varchar(255) NULL,
    cr_parish varchar(255) NULL,
    cr_village varchar(255),
    origin_nationality varchar(255) NULL,
    origin_tribe varchar(255) NULL,
    porigin_clan varchar(255) NULL,
    origin_religion varchar(255) NULL,
    school_name varchar(255) NULL,
    year_of_attendance varchar(255) NULL,
    last_grade_completed varchar(255),
    guardian_name varchar (255),
    guardian_relationship varchar(255) NULL,
    guardian_residence varchar(255),
    guardian_marital_status varchar(255),
    guardian_no_of_dependants varchar(255),
    guardian_occupation varchar(255),
    guardian_contact_no int(10) NULL,
    guardian_vulnerabilities varchar(255),
    depandants_at_home varchar(255),
    age int(10) NULL,
    reason_for_admission varchar(255),
    paternal_name varchar(255),
    paternal_residence varchar(255),
    paternal_relationship varchar(255),
    paternal_date_of_death DATE,
    paternal_cause_of_death varchar(255),
    paternal_occupation varchar(255),
    maternal_name varchar(255),
    maternal_residence varchar(255),
    maternal_relationship varchar(255),
    maternal_date_of_death DATE,
    maternal_cause_of_death varchar(255),
    maternal_occupation varchar(255),
    more_about_child varchar(255),
    childs_fav_game varchar(255),
    childs_fav_subject varchar(255),
    childs_career_goals varchar(255),
    siblings_at_path varchar(255),
    PRIMARY KEY (id)
)